### ISSUE TITLE
Making a column mandatory after db is created makes it last

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#114]
Making a column mandatory after db is created makes it last column in entity browser and forms.

**Comment by gkahiu** [comment]
The logic in the entity configuration does not change the column order, I suspect it is an issue related to the logic probably, the column is removed and re-inserted with the new settings. @pgathogo please shed more light on this.

**Comment by wondie** [comment]
But when I saw the database, the column is on its original order, even though it has gone to last on entity browser or forms.

**Comment by gkahiu** [comment]
Dear Wondie,

As I suspected, the ColumnEditor is removing the column and re-creating it
(if column is being edited) hence it is inserted at the end of the queue,
see reference here
<https://github.com/gltn/stdm/blob/ref_config_mod/ui/wizard/column_editor.py#L621>.
The database will not change the order since in reality the column is not
being removed. I trust it explains your current issue.

Include it as part of your discussion with Paul during the code review
meeting.

Regards,

John

**Comment by wondie** [comment]
Dear John, 

We will include it in tomorrow's review. I hope it is possible to modify the columns without postgres crash.

**Comment by pgathogo** [comment]
Fixed. The ColumnEditor no longer removes a column when doing an edit. All columns maintain their creation positions during editing.
