### ISSUE TITLE
Issues with Spatial Unit Editor

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#130]
I have noticed a couple of issues with the editor form for spatial units:
- The form has no parent widget hence it appears as a separate window;
- When I digitized and clicked OK, I assumed all the inputted data was correct and the form closed. However, when I was trying to commit changes, the QGIS message bar inserted a notification that there a mandatory field which was null. Hence, the form should check that all mandatory fields have been populated before accepting the dialog.

**Comment by wondie** [comment]
1. The form is handled by QGIS. So the behavior is the same as the default Form with no STDM widget added. Unfortunately, there is limited control of the form UI. There is a possibility of setting the parent but the operation is done for each number of columns. This might not be desirable performance wise. 

2. That seems to be a known issue for QGIS. layer.editFormConfig().setNotNull(idx, True) was tested and it had no effect in mandatory fields. Thus, I have disabled that line of code. As a result, untill QGIS fix this issue, we have to relay on PostgreSQL error.

**Comment by gkahiu** [comment]
Noted:

   - Setting parent on each column widget will not work but I believe we
   can set for the overall form. Need to check how QGIS creates it.
   - Lets explore further as this not null message is hidden inside the
   message bar and chances that the user will not find it are quite high

**Comment by wondie** [comment]
Oh I see. The creation of STDM widget for every field is like a loop and if a code is added, it will run it for every field and the last run will affect the interface. I was only above to the the Form dialog in QGIS 2.14. In QGIS 2.8, it is not accessible. 

I am already doing that when setting the WindowTitle, you can see the code [here](https://github.com/gltn/stdm/blob/ref_config_mod/ui/forms/spatial_unit_form.py#L180). Considering the benefit, I can test how it behaves and incorporate it. But it might be hard to know the performance as users Computers will come with wide range of performance.

**Comment by wondie** [comment]
Unfortunately, 
`self.parent.parent().setParent(iface.mainWindow())`
Led to the following interface. 

![image](https://cloud.githubusercontent.com/assets/9709624/16963704/6c797e24-4e00-11e6-9cb9-4431e4d532b8.png)

**Comment by wondie** [comment]
There is a major update in this issue. I worked on integrating STDM Form with QGIS Digitizing tool and it worked well. The behavior is similar to the GPX import with slight changes. 

Below is the implimentation

- A QGIS command suppresses QGIS forms when a feature is digitized and created. 

- [Then the STDM form loads](https://github.com/gltn/stdm/blob/7575b9f4256d066faa5b2910877f4c014e377cf3/ui/forms/spatial_unit_form.py#L328) in stead of QGIS form. 

- Then the once saved, the STDM Form saves the feature and the attribute date, together with the supporting document. 
- The editing session is rollbacked as if no change has happened, to prevent QGIS to also try to save the same feature. 
- Then the editing session is re-started again so that the user continue to add features. 

I feel this will make digitizing more complete than using QGIS Forms.

**Comment by gkahiu** [comment]
Cool, I will test and revert.

Regards,

John

**Comment by gkahiu** [comment]
I have quickly tested the new forms, though the forms are good, it is not consistent with QGIS behaviour because the record is automatically saved in the database, the user cannot rollback using the digitizing tools. I do not have a solution right now but I would prefer if we make the behaviour consistent when using QGIS digitizing tools and weigh the pros and cons of each option.

**Comment by wondie** [comment]
It is tricky to follow QGIS Digitizing behavior because we need to modify the behavior of the the form. When someone click the save button, in case of spatial units, instead of the saving it to database, we have to keep it in memory until the user clicks on the save button on the QGIS Digitizing toolbar. 

Then we can connect a slot to beforeCommitChanges signal, that will do the actual saving. 

More work needs to be done to remove records that the user removed with the Undo button, added again with the redo button.

**Comment by wondie** [comment]
I am currently working on your suggestion. I will report back if it works well.

**Comment by wondie** [comment]
I have now updated the behavior of the form. It is behaving just like QGIS default digitizing with undo, redo and save commands of QGIS working instead of the form. Then form's save button only collects the feature id and model in an OrderedDIct. 

@gkahiu could you test it and comment.

**Comment by gkahiu** [comment]
Apologies for taking long to respond. I have tested it and the interface looks fine.

However, when I right-click the layer and choose to open the attribute table then QGIS crashes. However, when I add the same layer using _Layer > Add Layer... > Add PostGIS Layer..._ then the 'open attribute' command works fine. 

So I suspect, the custom forms might have something to do with it.

**Comment by wondie** [comment]
That is ok. 

On which version of QGIS are you having the issue?

**Comment by gkahiu** [comment]
2.14.

In initially tried with 2.8 but QGIS was crashing when I finish digitizing
by right-clicking.

**Comment by wondie** [comment]
Ok, I tested 2.14 and I had no issue of opening the attribute table. I will test 2.8 and report back.

**Comment by wondie** [comment]
@gkahiu is this issue still not fixed?

**Comment by gkahiu** [comment]
It is working ok now in QGIS 2.14. Can you confirm that it is working in 2.8?

**Comment by wondie** [comment]
Ok good. Few methods that were used to load STDM Form are new and didn't exist in QGIS 2.8. I tried to use depreciated methods compatible with 2.8 but it couldn't work. However, the earlier form that uses QGIS form and STDM widgets works instead.

**Comment by gkahiu** [comment]
The reason am asking is so that we set the minimum version and I would
rather stick to 2.14 instead of 2.8.

**Comment by wondie** [comment]
I think we can recommend 2.14 but allow users to upgrade from 2.8 too as all the features with the exception of spatial unit form works. Even in that case, they will only miss uploading supporting documents and multi-select lookups that can be done while editing.

**Comment by wondie** [comment]
@gkahiu did you decide on the version?

**Comment by gkahiu** [comment]
Lets stick to 2.14 otherwise, 2,8 is unstable.

**Comment by wondie** [comment]
That is true but the problem is, when users update from STDM from 1.1 to 1.2 they have to first install QGIS 2.14 or they will get QGIS plugin incompatibility error. They have to update QGIS by themselves to use STDM. Is that acceptable for the user? 

Another thing is, until stdm plugin is stored in .qgis folder, users can't get plugin update notification. How could we achieve that?

**Comment by gkahiu** [comment]
Yes upgrading is mandatory. What is better - using current version of QGIS
2.8 with no guarantee of stability or upgrading to QGIS 2.14 with
predictable behavior?

It is stored in .qgis2 and yes, they will get plugin update notification.

**Comment by wondie** [comment]
I agree. It is better to force QGIS 2.14 as far as users can upgrade to stdm 1.2 without coming to gitHub.
