### ISSUE TITLE
In Document Generator is 'Use matching records in data source ..' option relevant now?

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#132]
Is the option  'Use matching records in data source ..' (highlighted in the image below) needed anymore? 
![image](https://cloud.githubusercontent.com/assets/9709624/17083007/2c8a12e0-519a-11e6-8693-e3bab3cc1e50.png)

**Comment by gkahiu** [comment]
Yes it is. It applies for single records which are computed from aggregates. For example, if there is a view that computes the total number of persons, then in such a case there is no need to add any records for a person since they are not applicable; hence the primary data source is the actual view that calculates the aggregate. 

So to answer your question, yes the option is still valid. Remember, the main reason we added a 'referenced_table' is just to filter templates based on the data source they refer to, otherwise the table is not referenced when generating the output document.

**Comment by wondie** [comment]
I see. So when check the checkbox, does it allow me to print a document without selecting any record?

**Comment by gkahiu** [comment]
Exactly with a specific design of the view.

**Comment by wondie** [comment]
I got it. But currently, with the default view vw_social_tenure_relationship, we don't need to use checkbox right?

**Comment by gkahiu** [comment]
No

**Comment by wondie** [comment]
That is noted.
