### ISSUE TITLE
Error shows up after upgrading

### ISSUE THREAD

**Issue by eomwandho** [gltn/stdm#143]
@gkahiu the error below shows up after upgrading when modules are being reloaded. The problem seems to arise because content base table already existed before the upgrade process started, from a previous installation and I'm assuming that when modules are being reloaded, values are being written to the same content base table that had entries from an old version of stdm.

![screenshot from 2016-07-28 18-12-03](https://cloud.githubusercontent.com/assets/2696951/17218012/04ad2c78-54ef-11e6-870f-485108e29427.png)

**Comment by gkahiu** [comment]
Are you also importing data to the _content_base_ table?

**Comment by eomwandho** [comment]
No.

**Comment by wondie** [comment]
@eomwandho  this issue happens because the old contents and the new ones are different. When I tried to escape the error, what happened was only few modules loaded. This shows the content_base and related tables are outdated. This issue can be fixed by dropping `content_base` and `content_roles `table inside config_file_updater.py, just after you call `import_data `method. 
Blow is the fix.

```
from ..data.pg_utils import safely_delete_tables
# Just after import_data(social_tenure_table, column_keys, values) drop the content tables
safely_delete_tables(['content_base', 'content_roles'])
```
Then content group re-creates the table and update its content with STDM 1.2 modules. 
I don't see a performance issue as this is done only once after upgrading the configuaration

**Comment by eomwandho** [comment]
@wondie I'm neither importing data or tables content_base or content_roles when upgrading. Dropping these tables will mean that the resulting function that uses them, will not have table to copy data into or read data from. A better solution could be to empty them or skip conflicting keys, which is something that can be address in the main repo.

**Comment by wondie** [comment]
At this point users haven't logged in. I have tested it and that is the best solution. We can look for other options if importing and using stdm 1.2 is affected. 
@gkahiu do you think dropping content tables will affect stdm?

**Comment by eomwandho** [comment]
@wondie the dropping of the table that you are suggesting is done after user has logged in.

**Comment by wondie** [comment]
Yes, after import_data method is called in config_file_updater.

**Comment by wondie** [comment]
@eomwandho did it work?

**Comment by gkahiu** [comment]
@eomwandho, did this issue get sorted?

**Comment by eomwandho** [comment]
The bug has not shown again, though it's not fixed. May be it only affects new installation, but deleting the content table might not be the optimal solution.

**Comment by wondie** [comment]
In that case, this issue can be closed.
