### ISSUE TITLE
Single page design and the ability to add multiple Social Tenure Relationship(STR) at once

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#162]
The Social Tenure Relationship Wizard takes time to add as users has to go through 6 wizard pages to save STR. 

I suggest to have a single page in which users can add a social tenure relationship. 
An STR entry will be a tree view with Social Tenure Relationship being the root. The party, spatial unit, tenure type, and supporting documents will be children of the root (see the images below). When each item is clicked, it shows a the existing data entry widgets.  

In relation, to this, the ability to add multiple STR makes the Social Tenure relationship faster to create several STR at once. Users can add more entries of STR to add as many STR as they want. 

The images below shows the suggested UI enhancement. 

The top Add and Delete button enable user to add and delete an STR entry. 

![image](https://cloud.githubusercontent.com/assets/9709624/18190167/43b08f46-70c9-11e6-8f5c-2ce7d95a11e2.png)

![image](https://cloud.githubusercontent.com/assets/9709624/18189933/992cb0f0-70c7-11e6-966e-1d7fc6f83c15.png)

![image](https://cloud.githubusercontent.com/assets/9709624/18190279/2b2c71dc-70ca-11e6-9be7-08ddef8f25e4.png)

![image](https://cloud.githubusercontent.com/assets/9709624/18189947/a869673e-70c7-11e6-8220-16437e10d325.png)

![image](https://cloud.githubusercontent.com/assets/9709624/18189952/afc273a4-70c7-11e6-8489-8f78bba0dd57.png)

**Comment by gkahiu** [comment]
This looks good, a few suggestions:

1. Save and Discard buttons to be aligned on the right.
2. It will be good if a label can be inserted at the top (before the main + and X buttons for adding a new social tenure relationship) to describe what happens or provide a quick overview of each page.

As already discussed, please remember that each UI should be treated as a client rather than having all the logic inside the UI. Focus should be on loosely coupled and modular code. As such, it would be great to see the class diagram accompanying this design.

All the best.

**Comment by wondie** [comment]
All the points are well noted. I will update the UI accordingly. I will post a class diagram here when ready.

**Comment by wondie** [comment]
This feature is included in the upcoming STDM 1.5 and can be found in master.
