### ISSUE TITLE
Couldn't open STDM Form because entity is None

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#191]
I created a profile and when I tried to access the Person entity form, I get the following error. 

```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'TYPE_INFO' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\entity_browser.py", line 811, in onNewEntity
    addEntityDlg = self._editor_dlg(self._entity, parent=self)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 130, in __init__
    self._init_gui()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 150, in _init_gui
    column_widget_area = self._setup_columns_content_area()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 287, in _setup_columns_content_area
    self._add_fk_browser(ch)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 348, in _add_fk_browser
    can_filter=True
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\foreign_key_mapper.py", line 209, in __init__
    self._init_fk_columns()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\foreign_key_mapper.py", line 271, in _init_fk_columns
    formatter = w_factory(c)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\widgets.py", line 545, in __init__
    self._p_entity_cls = entity_model(p_entity, entity_only=True)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\configuration\__init__.py", line 65, in entity_model
    if entity.TYPE_INFO == 'ENTITY_SUPPORTING_DOCUMENT':
AttributeError: 'NoneType' object has no attribute 'TYPE_INFO'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

```
I am able to access the entity browser.

**Comment by wondie** [comment]
Please find the attached configuration.
[configuration (2).zip](https://github.com/gltn/stdm/files/551227/configuration.2.zip)

**Comment by gkahiu** [comment]
I had a look at this and the problem is from a faulty configuration section:
```
<Column unique="False" tip="The person deciding on the application" minimum="0" maximum="2147483647" description="The person deciding on the application" index="False" name="decider_id" searchable="False" TYPE_INFO="FOREIGN_KEY" mandatory="False">
     <Relation name="_ug_application_approval_decider_id"/>
</Column>
```
Specifically, the Relation name attribute is not well formed since it should have a **fk** prefix to depict that it is a foreign key. Am not sure as to how this came about but as a workaround, could you delete this column and recreate it afresh. Also, it will be good if you could try reproduce it so that we can try to trace the source of incomplete configuration serialization, if this indeed is the case.

In the meantime, I will fix the None entity issue to give a more subtle notification.

**Comment by wondie** [comment]
I am glad that the cause is found. Thank you! I think the reason why this happened is because, I deleted the parent entity called decider from within the configuration.stc.
However, when I deleted a parent entity using the wizard, it kept the child column as it is, with a normal relation name but the entity browser of the child entity couldn't be opened because the parent entity doesn't exist.

**Comment by gkahiu** [comment]
I have pushed a commit in master to handle issues when creating RelatedEntity widgets, if the parent (in an EntityRelation) is not found, then an error message is shown and the corresponding widget will not be added to the form.

**Comment by wondie** [comment]
That is good. I will test and report.

**Comment by wondie** [comment]
However, the strange thing is, even though the problematic column existed in adjudication entity, the error of entity is none is shown in party and spatial unit entity.

**Comment by gkahiu** [comment]
When an entity form is loaded, the system searches for all relationships so that they can be managed from the form. In the case of your configuration, the definition of the Application_approval entity is as excerpted below:
```
<Entity editable="True" global="False" associative="False" description="Application approval refers to decision and decider, and related person and plot. " documentTypeLookup="check_application_approval_document_type" proxy="False" createId="True" supportsDocuments="True" shortName="Application_approval" name="ug_application_approval">
   <Columns>
    <Column unique="False" tip="" minimum="-2147483648" maximum="2147483647" description="" index="False" name="id" searchable="True" TYPE_INFO="SERIAL" mandatory="False"/>
    <Column unique="False" tip="The approval status of the application." minimum="0" maximum="2147483647" description="The approval status of the application." index="False" name="approval_status_id" searchable="True" TYPE_INFO="LOOKUP" mandatory="False">
     <Relation name="fk_ug_check_approval_status_id_ug_application_approval_approval_status_id"/>
    </Column>
    <Column unique="False" tip="The terms and conditions related to the decision." minimum="0" maximum="1073741823" description="The terms and conditions related to the decision." index="False" name="approval_terms_and_conditions" searchable="False" TYPE_INFO="TEXT" mandatory="False"/>
    <Column unique="False" tip="The applicant of ownership to the plot." minimum="0" maximum="2147483647" description="The applicant of ownership to the plot. " index="False" name="person_id" searchable="False" TYPE_INFO="FOREIGN_KEY" mandatory="False">
     <Relation name="fk_ug_person_id_ug_application_approval_person_id"/>
    </Column>
    <Column unique="False" tip="The plot claimed by the applicant" minimum="0" maximum="2147483647" description="The plot claimed by the applicant" index="False" name="plot_id" searchable="False" TYPE_INFO="FOREIGN_KEY" mandatory="True">
     <Relation name="fk_ug_plot_id_ug_application_approval_plot_id"/>
    </Column>
    <Column unique="False" tip="The person deciding on the application" minimum="0" maximum="2147483647" description="The person deciding on the application" index="False" name="decider_id" searchable="False" TYPE_INFO="FOREIGN_KEY" mandatory="False">
     <Relation name="_ug_application_approval_decider_id"/>
    </Column>
   </Columns>
  </Entity>
```
You will notice that there are two foreign key columns i.e. person_id and plot_id, hence when the person or plot form is being loaded, the system is attempting to create a back reference to the application approval entity so that it can create a foreign key mapper instance. However, when the foreign key mapper is being initialized, it encounters an invalid reference to the decider_id which results in the error.

That said, the exception handling that I pushed will first show an error message then load the form minus the relation widget as illustrated below:
![widget creation error](https://cloud.githubusercontent.com/assets/3840267/19781411/cc0a151c-9c91-11e6-9742-8485c5e1a353.PNG)

then the form:
![plot editor](https://cloud.githubusercontent.com/assets/3840267/19781424/d6bf964e-9c91-11e6-95ae-899061c874c3.PNG)

I hope its clear.

**Comment by wondie** [comment]
This is clear. Thank you for the fix!
