### ISSUE TITLE
User Guide, STDM Release 1.0, v17.12.2014 needs update (so far for the pages 1-25) 

### ISSUE THREAD

**Issue by vioannidi** [gltn/stdm#20]

**Comment by SolomonN** [comment]
Hi Vioannidi,Yes, the documentation is not updated on some sections. This is noted and will be revised. Kind Regards,
Solomon.Mobile +254 724 291046 

     On Friday, February 27, 2015 8:27 PM, vioannidi <notifications@github.com> wrote:
   

    
   - A general remark concerning the guide up to page 25 is that the screen-dumps are quite often not in accordance with the text referring to them. It would be nice for the first time user to be able to find the new tables/fields that he/she is supposed to create back in these screen-dumps.
   - Page 10, line 1: there is no "Basic" default profile to be found in the configuration wizard. Therefore the 1st paragraph of this page does not make sense. Did the writer of the guide mean to write "stdm" instead of "basic" ?
   - Page 12, line 3-4: There are not any tables with names "water points" and "services".
   - As a new user of STDM I would have appreciate it if I was able to follow steps to build up a new database and populate it with the necessary tables/columns/ lookup columns etc. instead of reading descriptions about what the function of the already created tables/columns/lookup columns is. 
   - On page 20 the reader of the guide is invited to create a new lookup column but this is already created in the stdm database. To be more specific, on that page I was supposed to create the lookup column “check_gender” and then add new choices to it (Male, Female) but this was already done. I tried to delete the check_gender lookup column in order to create it from scratch but I was not allowed to do that (I guess this is due to some kind of constraint added to this table).
Next week, I will proceed with the rest of the guide (pages 26 - 89) and I will report new issues if necessary.—
