### ISSUE TITLE
Enabling the Appearance options in the attribute table Item properties in Designer

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#203]
I discovered that the [Appearance options](https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_attribute_table.html#appearance) box has few useful settings to customize the attribute table. 
The empty rows can be created based if the "Show empty rows" is checked as shown in the image below. 
The option of wrapping text is very useful to restrict the size of tables that could grow beyond the paper size. 
Background color is also very useful. 
![image](https://cloud.githubusercontent.com/assets/9709624/20682911/0899745e-b5bb-11e6-9d68-32c0b84f4a35.png)

**Comment by wondie** [comment]
I looked at the QgsComposerAttributeTable but there is no option to enable the appearance groupbox. I then checked the class [TableFormatter ](https://github.com/gltn/stdm/blob/master/composer/item_formatter.py#L247)in item_formatter.py in composer folder. However, that class don't turn off the appearance groupbox with the object name **groupBox_6**. I tried to print the group box but it returns **None**. It seems like there is something else removing it. I hope it is you than QGIS.

**Comment by gkahiu** [comment]
The table with an 'Appearance' option is an enhanced version of the QgsComposerAttributeTable class, i.e. QgsComposerAttributeTableV2 which provides more capabilities. In order to incorporate it in STDM's custom attribute table, change [this](https://github.com/gltn/stdm/blob/master/composer/composer_item_config.py#L251) line of code to:
```
self.composerView().setCurrentTool(QgsComposerView.AddAttributeTable)
```
However, please note that the API has changed and as a result, the dependent code snippets might be referencing redundant functions in the old API, see [here](http://qgis.org/api/2.14/classQgsComposerAttributeTable.html). Hence, please check all code sections for the attribute table and revise to reflect the new API where applicable; see the new API [here](http://qgis.org/api/2.14/classQgsComposerAttributeTableV2.html). Also test extensively including (de)serialization from/to _*.sdt_ files.

**Comment by wondie** [comment]
wow, that is nice. I made the change as you have suggested and the appearance option box is now visible but the STDM item properties is empty.

**Comment by gkahiu** [comment]
This is the side effect I was referring to because of old references. Hence, the reason you cannot edit STDM item properties because [this](https://github.com/gltn/stdm/blob/master/composer/item_formatter.py#L252) code is now invalid. Hence, it should read:
```
if not isinstance(table_item, QgsComposerAttributeTableV2):
            return
```
Remember to import QgsComposerAttributeTableV2 first.

As indicated, you need to check all references of the old API and update accordingly.

**Comment by wondie** [comment]
Unfortunately, it still doesn't work. What happened is, when I add using add attribute table button, it adds QgsComposerFrame instead of QgsComposerAttributeTableV2.

**Comment by wondie** [comment]
Everything works well now except hiding some unneeded widgets from the **item properties** dock. The ones that couldn't be hidden are the Qgs widget specifically QgsMapLayerComboBox. Even though it inherits from QComboBox, I think they have disabled some methods such as setHidden, setVisible, etc. I also checked [the API](https://qgis.org/api/classQgsMapLayerComboBox.html#details), but there is no method to hide it.

**Comment by gkahiu** [comment]
setVisible(False) should work since they all inherit from QWidget.

**Comment by wondie** [comment]
Yea but it is not working for QGIS widgets.
