### ISSUE TITLE
Couldn't import into admin_spatial_unit

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#204]
I integrated the admin_spatial_unit_set table to be imported and exported. Unfortunately, the import is not working with the following error. 
CSV table:
```
id,parent_id,name,code
1,,Uganda,UG
2,1,Eastern,EA
3,2,Soroti,So
4,3,Arapai,ARA
5,4,Agirigiroi,AGI
6,5,Abilangiti,ABI
7,5,Agaya,AGA
```
Error message:
![image](https://cloud.githubusercontent.com/assets/9709624/20689533/f6e182e4-b5d6-11e6-8243-8a3262de92c2.png)

I have tried adding, **NULL, DEFAULT, 0, 1** but none of them worked.

**Comment by gkahiu** [comment]
Separate your CSV data so that you have one CSV file for highest level administrative units i.e. those that do not have any parent, that way you will not have to import to the parent_id column and will only be concerned with importing the name and code only. Then prepare a separate CSV containing the children administrative units; in this case, arrange the administrative units based on hierarchy level i.e. level one units at the top followed by level two units followed by level _n_ units and this is because the importation is done sequentially based on the row position.

Also, do not import the primary keys as it is upto the database engine to determine which ids to assign to rows. To ensure that the parent-child relationship of the units is maintained, use the name or code of the parent unit then configure the importation to the parent_id column to use the Related Table translator. Hence, the resulting CSV should be more or less similar to the illustration below:

**CSV ONE** (no parent):
```
name,code
Uganda,UG
```

**CSV TWO** (using code to identify the parent then import using Related Table translator):
```
parent_id,name,code
UG,Eastern,EA
EA,Soroti,So
So,Arapai,ARA
ARA,Agirigiroi,AGI
AGI,Abilangiti,ABI
AGI,Agaya,AGA
```

Another observation when it comes to naming of the highest administrative unit, I would strongly suggest you exclude the country since it is obvious that all administrative units will be in Uganda for example. Unless, it is a regional (inter-country) implementation then the inclusion of the country introduces redundancies in the coding while also making a long code which can be shortened by excluding the county code e.g. UG. Hence, the top most administrative units should be the ones that fall below national level e.g. counties in the case of Kenya.

**Comment by wondie** [comment]
I got you well. However, how could I get csv 2 when I export from the STDM datatabase?

**Comment by gkahiu** [comment]
Create a view that converts the parent_ids to the actual names then export
that view to csv.

**Comment by wondie** [comment]
Ok.
