### ISSUE TITLE
Unable to create a new Admin spatial unit

### ISSUE THREAD

**Issue by SolomonN** [gltn/stdm#237]
Says duplicate key exist but the name does not exist

IntegrityError: (IntegrityError) duplicate key value violates unique constraint "admin_spatial_unit_set_pkey" DETAIL:  Key (id)=(4) already exists. 'INSERT INTO admin_spatial_unit_set (parent_id, name, code) VALUES (%(parent_id)s, %(name)s, %(code)s) RETURNING admin_spatial_unit_set.id' {'parent_id': None, 'code': u'Nai', 'name': u'Nairobi'}

**Comment by wondie** [comment]
Were you trying to import data like csv?

**Comment by SolomonN** [comment]
No Wondie, I was creating a new entry from the dialog :Manage Administrative units

**Comment by wondie** [comment]
The error means the the table's sequence is not in sync. As a result it
doesn't know the correct next id value.

What I suggest is to update the sequence after running a data import on
each table.
The following code can help.

t = text('SELECT setval({0}_name_id_seq, (SELECT MAX(id) FROM
{0}'.format(table_name))
result = _execute(t)


On Jun 30, 2017 14:00, "Solomon Njogu" <notifications@github.com> wrote:

No Wondie, I was creating a new entry from the dialog :Manage
Administrative units

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/gltn/stdm/issues/237#issuecomment-312239351>, or mute
the thread

**Comment by gkahiu** [comment]
Try Wondie's solution, I also suspect that it might be related to the primary key sequencing.
