### ISSUE TITLE
The unique option in the column editor is not working for geometry data types

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#258]
The column editor has the unique option enabled by default but it is not creating the unique constraint in the data. 
![image](https://user-images.githubusercontent.com/9709624/30012943-1fce002a-9163-11e7-9474-e71e5669b6ee.png)

Please, see the create query of the table. 
```
-- Table: public.do_house

-- DROP TABLE public.do_house;

CREATE TABLE public.do_house
(
  id integer NOT NULL DEFAULT nextval('do_house_id_seq'::regclass),
  type_of_land_of_current_house integer,
  gps_point_file_name_of_current_house character varying(30),
  nra_number character varying(100),
  received_beneficiary_number integer,
  beneficiary_number character varying(100),
  receive_grant_for_reconstruction integer,
  petition_applied integer,
  reason_for_not_applying text,
  current_house_status integer,
  current_parcel_cadastral_number character varying(100),
  area_of_current_house numeric(18,2),
  current_house_photo_file_name character varying(30),
  current_house_same_as_pre_earthquake integer,
  previous_house_status integer,
  previous_parcel_cadastral_number character varying(100),
  area_of_previous_house numeric(18,2),
  point geometry(Point,4326),
  type_of_land_of_previous_house integer,
  CONSTRAINT do_house_pkey PRIMARY KEY (id),
  CONSTRAINT do_house_current_house_same_as_pre_earthquake_fkey FOREIGN KEY (current_house_same_as_pre_earthquake)
      REFERENCES public.do_check_yes_no (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_current_house_status_fkey FOREIGN KEY (current_house_status)
      REFERENCES public.do_check_current_house_status (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_petition_applied_fkey FOREIGN KEY (petition_applied)
      REFERENCES public.do_check_yes_no (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_previous_house_status_fkey FOREIGN KEY (previous_house_status)
      REFERENCES public.do_check_previous_house_status (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_receive_grant_for_reconstruction_fkey FOREIGN KEY (receive_grant_for_reconstruction)
      REFERENCES public.do_check_yes_no (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_received_beneficiary_number_fkey FOREIGN KEY (received_beneficiary_number)
      REFERENCES public.do_check_yes_no (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_type_of_land_of_current_house_fkey FOREIGN KEY (type_of_land_of_current_house)
      REFERENCES public.do_check_type_of_land (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT do_house_type_of_land_of_previous_house_fkey FOREIGN KEY (type_of_land_of_previous_house)
      REFERENCES public.do_check_type_of_land (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.do_house
  OWNER TO postgres;

-- Index: public.idx_do_house_point

-- DROP INDEX public.idx_do_house_point;

CREATE INDEX idx_do_house_point
  ON public.do_house
  USING btree
  (point);


```
Luckily, this bug helped me in the Nepal project as one geometry (house) was shared by different household and we had to enter duplicate geometry. 

Thus, what I suggest is the following:
1. Fix the issue of Unique option not creating the Unique constraint in the database.
2. Check the Unique option for geometry columns by default but not disable it as shown in the image above.

**Comment by gkahiu** [comment]
Does the _Unique_ option not work for all (applicable) data types or just for _Geometry_ type columns?

**Comment by wondie** [comment]
Yes, for farm polygon too.

**Comment by gkahiu** [comment]
It works for non-spatial data types with an example of the character varying type, see highlighted sections in the screenshots below:

![image](https://user-images.githubusercontent.com/3840267/30015775-e95b1152-915a-11e7-914b-2d66be6b83d8.png)

![image](https://user-images.githubusercontent.com/3840267/30015755-d56b9ec8-915a-11e7-8473-50f35f91c241.png)

That said, the _Unique_ option should, by default, be disabled (as it is now) and **unchecked** for _Geometry_ data types because geometry types cannot be unique based on the complexity of their data structure. For instance, we might be tempted to say that a point is unique if the X, Y coordinates are equal but then again we find that geographic coordinate values have a large scale of, say 8 decimal places, hence a value like 23.9876543**2** will not be unique when compared to 23.9876543**3** just because the last digit is different but then visually they will appear the same at a zoomed out level yet the user would expect the constraint to be valid based on the visual interpretation. This even becomes more prominent when digitizing overlaid features because the probability of having different values is much higher. If we extrapolate this constraint to other geometry types then it becomes even more complicated:

- Lines and polygons are made up of a series of points so if we analyze the uniqueness of a line or a polygon based on X,Y coordinate values being the same for all points, then the probability of uniqueness will be far much lower. For example, if we take a polygon feature A having 4 points and compare it with feature B having the same outline as feature A but with 5 points, then the uniqueness of the two will fail on two fronts: first, the number of coordinate pairs will be different i.e. 4 vs 5, and second, the probability of the four common points being the same will be much lower as discussed above. See illustration below:

![image](https://user-images.githubusercontent.com/3840267/30017244-1bd4e2ce-9161-11e7-81c0-50bce23b368d.png)

My point is, enforcing uniqueness for geometry data types is complex and might beat the purpose when compared to other basic data structures. That is why topology is used for geometry structures as it defines the relationship between points, lines and polygons in a cartesian plane. I would suggest that the QGIS topology checker is used to validate for point and polygon types in your use case as there are different rules for different vector types, see more details [here](http://docs.qgis.org/2.18/en/docs/user_manual/plugins/plugins_topology_checker.html).

@pgathogo please uncheck the uniqueness option when a geometry data type is selected.

**Comment by wondie** [comment]
I understand your point. It is complex and a rare case when digitizing. However, duplicate entry happens in STDM especially when importing GPS features. I have come across duplicate entry errors when the Unique option was working in the earlier versions. I feel that is useful in that case.

**Comment by gkahiu** [comment]
Please see my comments/questions in bold:

I understand your point. It is complex and a rare case when digitizing. However, duplicate entry happens in STDM especially when importing GPS features. 
**- Duplicate geometries or duplicate values for non-spatial data types?**

I have come across duplicate entry errors when the Unique option was working in the earlier versions. 
**- Duplicate errors for geometries or non-spatial data types? Which version of STDM? Could you recreate the environment in one of these versions and send the SQL Create statement for the applicable table?**

I feel that is useful in that case.
**- Have you looked at Topology Checker, topology checks are the recommended way of validating GEOMETRY data.**

**For your use case, I would suggest you design additional geometry validation workflows prior to importing the data into STDM.**

**Comment by wondie** [comment]
1. Duplicate geometries in case of duplicate GPS Importing or even repeated importing spatial data. 
2. For spatial data type. Version 1.5. 

```
-- Table: public.ko_garden

-- DROP TABLE public.ko_garden;

CREATE TABLE public.ko_garden
(
  id integer NOT NULL DEFAULT nextval('ko_garden_id_seq'::regclass),
  garden_id character varying(4000),
  district integer,
  county integer,
  sub_county integer,
  parish integer,
  village integer,
  block integer,
  unit_name integer,
  type_of_land integer,
  written_tenure_agreement integer,
  form_of_agreement integer,
  garden_eastings character varying(30),
  garden_northings character varying(30),
  spatial_geometry geometry(Polygon,4326),
  CONSTRAINT ko_garden_pkey PRIMARY KEY (id),
  CONSTRAINT ko_garden_block_fkey FOREIGN KEY (block)
      REFERENCES public.ko_check_block (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_county_fkey FOREIGN KEY (county)
      REFERENCES public.ko_check_county (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_district_fkey FOREIGN KEY (district)
      REFERENCES public.ko_check_district (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_form_of_agreement_fkey FOREIGN KEY (form_of_agreement)
      REFERENCES public.ko_check_form_of_agreement (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_parish_fkey FOREIGN KEY (parish)
      REFERENCES public.ko_check_parish (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_sub_county_fkey FOREIGN KEY (sub_county)
      REFERENCES public.ko_check_sub_county (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_type_of_land_fkey FOREIGN KEY (type_of_land)
      REFERENCES public.ko_check_type_of_land (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_unit_name_fkey FOREIGN KEY (unit_name)
      REFERENCES public.ko_check_unit_name (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_village_fkey FOREIGN KEY (village)
      REFERENCES public.ko_check_village (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ko_garden_written_tenure_agreement_fkey FOREIGN KEY (written_tenure_agreement)
      REFERENCES public.ko_check_agreement (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT unq_ko_garden_spatial_geometry UNIQUE (spatial_geometry)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.ko_garden
  OWNER TO postgres;

-- Index: public.idx_ko_garden_garden_id

-- DROP INDEX public.idx_ko_garden_garden_id;

CREATE INDEX idx_ko_garden_garden_id
  ON public.ko_garden
  USING btree
  (garden_id COLLATE pg_catalog."default");


```
3. I have looked for it. But I feel the unique constraint for geometry worked. I have explored topology checker, but having a basic feature of duplicate entry checking is useful. 

There is a plan for STDM 2.0 to have a geometry validation feature which includes more checks but that might take time.

**Comment by gkahiu** [comment]
Did the unique constraint work for point, line or polygon features? Have you tried checking the 'uniqueness' of the geometry column (say by digitizing or importing GPS features) in the table created by the SQL statement that you have posted?

**Comment by wondie** [comment]
Yes, it worked for all feature types. I tested by importing GPS features and importing shapefiles.

**Comment by gkahiu** [comment]
Please send me the sample datasets so that I can test on this end.

**Comment by wondie** [comment]
You can use the sample data shapefile and the gpx files in STDM 1.5.

**Comment by wondie** [comment]
This issue is now fixed.
