### ISSUE TITLE
The desgin forms wizard and StdmConfiguration class couldn't load saved after QGIS restart

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#46]
The profile and entities details do not loaded in the design forms wizard after QGIS restart despite running the design forms wizard successfully. The file configuration.stc exists in user Directory/.stdm with the last created profile.

Most importantly, the StdmConfiguration.instance() couldn't load any profile using self.profiles property and self.profile() method. Both return empty results, empty OrderDict() and None respectively.

**Comment by gkahiu** [comment]
I have updated the code to load the configuration from file. However, eve
though the entities are loaded correctly in the wizard, there is an error
when updating the schema if the the database is empty. I am posting an
issue for Paul to look at.

That said, you can now access the profiles attribute of configuration
instance. Please test and confirm. You can also call current_profile method
to read the current profile name from the registry and return the
corresponding Profile object if it exists in the collection, otherwise it
will return None.

**Comment by wondie** [comment]
I have confirmed that the it is working!
