### ISSUE TITLE
document type column is added in social_tenure_relationship_supporting_document and other entities

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#90]
Document type column was previously located in supporting_document table. However, it doesn't have constraint as reported in [issue 87](https://github.com/gltn/stdm/issues/87) . Now, after pulling the latest commit, I found out that document type column is also added in  other entities supporting document and social_tenure_relationship_supporting_document. In my view, it is more convenient to keep it in supporting_document table. However, if there is a reason for it, is good to have one column.

**Comment by gkahiu** [comment]
The one stored in the supporting_document table represents a type that is
associated with an entity within profile whereas the types in the
supporting documents represent the sub-types within an entity otherwise if
we have all types under supporting documents then we cannot enforce
referential integrity and as such, will be difficult to associate one types
from the entities they refer to. So think of it as a logical grouping. I
hope it is clear.

Regards,

John

**Comment by wondie** [comment]
I now get why is needed to have it in each entities. What is the importance of document type column in the  supporting_document table. With which lookup is it linked?

**Comment by gkahiu** [comment]
That represents the document type at entity level and is also used when to
get a reference to the folder (under the root folder for saupporting
documents) where the supporting documents for a given entity are located.

**Comment by wondie** [comment]
I have noted that. Thank you!
